### ISSUE TITLE
Add setting to only show checks in areas you have the map for

### ISSUE THREAD

**Issue by thislooksfun** [syyePhenomenol/HollowKnight.APMapMod#1]
With this mod enabled, randomizing the maps loses some of its effectiveness. It would be fun to be able to set this mod to only show checks areas that you have unlocked the map for, rather than unlocking the whole map at once.

**Comment by syyePhenomenol** [comment]
In the Pause Menu, you can toggle the mode to "Pins Over Map". Hopefully this is what you want.

**Comment by syyePhenomenol** [comment]
By the way, this repository is very outdated. The latest version of APMapMod can be found here: https://github.com/KonoTyran/HollowKnight.ArchipelagoMapMod

**Comment by thislooksfun** [comment]
Oh lol, I didn't realize this wasn't the version I had installed. I'll give the "pins over map" mode a try!
